#pragma once

#include <cstdint>
#include <string>

#define S3_OPENSSL_USE_C_API // openssl API: C

namespace s3
{
    enum class S3ApiKind : int32_t
    {
        Unknown,
        AbortMultipartUpload,
        CompleteMultipartUpload,
        CopyObject,
        CreateBucket,
        CreateBucketMetadataConfiguration,
        CreateBucketMetadataTableConfiguration,
        CreateMultipartUpload,
        CreateSession,
        DeleteBucket,
        DeleteBucketAcl,
        DeleteBucketAnalyticsConfiguration,
        DeleteBucketCors,
        DeleteBucketEncryption,
        DeleteBucketIntelligentTieringConfiguration,
        DeleteBucketInventoryConfiguration,
        DeleteBucketLifecycle,
        DeleteBucketMetadataConfiguration,
        DeleteBucketMetadataTableConfiguration,
        DeleteBucketMetricsConfiguration,
        DeleteBucketOwnershipControls,
        DeleteBucketPolicy,
        DeleteBucketReplication,
        DeleteBucketTagging,
        DeleteBucketWebsite,
        DeleteObject,
        DeleteObjectTagging,
        DeleteObjects,
        DeletePublicAccessBlock,
        GetBucketAbac,
        GetBucketAccelerateConfiguration,
        GetBucketAcl,
        GetBucketAnalyticsConfiguration,
        GetBucketCors,
        GetBucketEncryption,
        GetBucketIntelligentTieringConfiguration,
        GetBucketInventoryConfiguration,
        GetBucketLifecycle,
        GetBucketLifecycleConfiguration,
        GetBucketLocation,
        GetBucketLogging,
        GetBucketMetadataConfiguration,
        GetBucketMetadataTableConfiguration,
        GetBucketMetricsConfiguration,
        GetBucketNotification,
        GetBucketNotificationConfiguration,
        GetBucketOwnershipControls,
        GetBucketPolicy,
        GetBucketPolicyStatus,
        GetBucketReplication,
        GetBucketRequestPayment,
        GetBucketTagging,
        GetBucketVersioning,
        GetBucketWebsite,
        GetObject,
        GetObjectAcl,
        GetObjectAttributes,
        GetObjectLegalHold,
        GetObjectLockConfiguration,
        GetObjectRetention,
        GetObjectTagging,
        GetObjectTorrent,
        GetPublicAccessBlock,
        HeadBucket,
        HeadObject,
        ListBucketAnalyticsConfigurations,
        ListBucketIntelligentTieringConfigurations,
        ListBucketInventoryConfigurations,
        ListBucketMetricsConfigurations,
        ListBucketObjects,
        ListBuckets,
        ListDirectoryBuckets,
        ListMultipartUploads,
        ListObjectVersions,
        ListObjects,
        ListObjectsV2,
        ListParts,
        PutBucketAbac,
        PutBucketAccelerateConfiguration,
        PutBucketAcl,
        PutBucketAnalyticsConfiguration,
        PutBucketCors,
        PutBucketEncryption,
        PutBucketIntelligentTieringConfiguration,
        PutBucketInventoryConfiguration,
        PutBucketLifecycle,
        PutBucketLifecycleConfiguration,
        PutBucketLogging,
        PutBucketMetricsConfiguration,
        PutBucketNotification,
        PutBucketNotificationConfiguration,
        PutBucketOwnershipControls,
        PutBucketPolicy,
        PutBucketReplication,
        PutBucketRequestPayment,
        PutBucketTagging,
        PutBucketVersioning,
        PutBucketWebsite,
        PutObject,
        PutObjectAcl,
        PutObjectLegalHold,
        PutObjectLockConfiguration,
        PutObjectRetention,
        PutObjectTagging,
        PutPublicAccessBlock,
        RenameObject,
        RestoreObject,
        SelectObjectContent,
        UpdateBucketMetadataInventoryTableConfiguration,
        UpdateBucketMetadataJournalTableConfiguration,
        UpdateObjectEncryption,
        UploadPart,
        UploadPartCopy,
        WriteGetObjectResponse,
    };

    const char* s3ApiKindToString(S3ApiKind apiKind) noexcept;
    S3ApiKind stringToS3ApiKind(const std::string& s) noexcept;
} // namespace s3
