#include "s3_error.hpp"

#include <unordered_map>
namespace s3
{
    const S3ErrorInfo& getS3ErrorInfo(S3ErrorCode s3ErrorCode)
    {
        using E = S3ErrorCode;
        static const std::unordered_map<E, S3ErrorInfo> kTable = {
            {E::AccessControlListNotSupported,
             {E::AccessControlListNotSupported, "AccessControlListNotSupported", "The bucket does not allow ACLs.", HttpStatusCode::BadRequest}},
            {E::AccessDenied, {E::AccessDenied, "AccessDenied", "Access Denied", HttpStatusCode::Forbidden}},
            {E::AccessPointAlreadyOwnedByYou,
             {E::AccessPointAlreadyOwnedByYou, "AccessPointAlreadyOwnedByYou",
              "An access point with an identical name already exists in your account.", HttpStatusCode::Conflict}},
            {E::AccountProblem,
             {E::AccountProblem, "AccountProblem",
              "There is a problem with your AWS account that prevents the operation from completing successfully.", HttpStatusCode::Forbidden}},
            {E::AllAccessDisabled,
             {E::AllAccessDisabled, "AllAccessDisabled", "All access to this Amazon S3 resource has been disabled.", HttpStatusCode::Forbidden}},
            {E::AmbiguousGrantByEmailAddress,
             {E::AmbiguousGrantByEmailAddress, "AmbiguousGrantByEmailAddress",
              "The email address that you provided is associated with more than one account.", HttpStatusCode::BadRequest}},
            {E::AuthorizationHeaderMalformed,
             {E::AuthorizationHeaderMalformed, "AuthorizationHeaderMalformed", "The authorization header that you provided is not valid.",
              HttpStatusCode::BadRequest}},
            {E::AuthorizationQueryParametersError,
             {E::AuthorizationQueryParametersError, "AuthorizationQueryParametersError",
              "The authorization query parameters that you provided are not valid.", HttpStatusCode::BadRequest}},
            {E::BadDigest,
             {E::BadDigest, "BadDigest", "The Content-MD5 or checksum value that you specified did not match what the server received.",
              HttpStatusCode::BadRequest}},
            {E::BucketAlreadyExists,
             {E::BucketAlreadyExists, "BucketAlreadyExists", "The requested bucket name is not available.", HttpStatusCode::Conflict}},
            {E::BucketAlreadyOwnedByYou,
             {E::BucketAlreadyOwnedByYou, "BucketAlreadyOwnedByYou", "The bucket that you tried to create already exists, and you own it.",
              HttpStatusCode::Conflict}},
            {E::BucketHasAccessPointsAttached,
             {E::BucketHasAccessPointsAttached, "BucketHasAccessPointsAttached", "The bucket you tried to delete has access points attached.",
              HttpStatusCode::BadRequest}},
            {E::BucketNotEmpty, {E::BucketNotEmpty, "BucketNotEmpty", "The bucket that you tried to delete is not empty.", HttpStatusCode::Conflict}},
            {E::ClientTokenConflict,
             {E::ClientTokenConflict, "ClientTokenConflict",
              "Your Multi-Region Access Point idempotency token was already used for a different request.", HttpStatusCode::Conflict}},
            {E::ConnectionClosedByRequester,
             {E::ConnectionClosedByRequester, "ConnectionClosedByRequester",
              "Returned to the original caller when an error is encountered while reading the WriteGetObjectResponse body.",
              HttpStatusCode::BadRequest}},
            {E::ConditionalRequestConflict,
             {E::ConditionalRequestConflict, "ConditionalRequestConflict", "A conflicting operation occurred.", HttpStatusCode::Conflict}},
            {E::CredentialsNotSupported,
             {E::CredentialsNotSupported, "CredentialsNotSupported", "This request does not support credentials.", HttpStatusCode::BadRequest}},
            {E::CrossLocationLoggingProhibited,
             {E::CrossLocationLoggingProhibited, "CrossLocationLoggingProhibited", "Cross-Region logging is not allowed.",
              HttpStatusCode::Forbidden}},
            {E::DeviceNotActiveError,
             {E::DeviceNotActiveError, "DeviceNotActiveError", "The device is not currently active.", HttpStatusCode::BadRequest}},
            {E::EndpointNotFound, {E::EndpointNotFound, "EndpointNotFound", "Direct requests to the correct endpoint.", HttpStatusCode::BadRequest}},
            {E::EntityTooSmall,
             {E::EntityTooSmall, "EntityTooSmall", "Your proposed upload is smaller than the minimum allowed object size.",
              HttpStatusCode::BadRequest}},
            {E::EntityTooLarge,
             {E::EntityTooLarge, "EntityTooLarge", "Your proposed upload exceeds the maximum allowed object size.", HttpStatusCode::BadRequest}},
            {E::ExpiredToken, {E::ExpiredToken, "ExpiredToken", "The provided token has expired.", HttpStatusCode::BadRequest}},
            {E::IllegalLocationConstraintException,
             {E::IllegalLocationConstraintException, "IllegalLocationConstraintException",
              "The specified location constraint is not valid for this request.", HttpStatusCode::BadRequest}},
            {E::IllegalVersioningConfigurationException,
             {E::IllegalVersioningConfigurationException, "IllegalVersioningConfigurationException",
              "The versioning configuration specified in the request is not valid.", HttpStatusCode::BadRequest}},
            {E::IncompleteBody,
             {E::IncompleteBody, "IncompleteBody", "You did not provide the number of bytes specified by the Content-Length HTTP header.",
              HttpStatusCode::BadRequest}},
            {E::IncorrectEndpoint,
             {E::IncorrectEndpoint, "IncorrectEndpoint", "The specified bucket exists in another Region.", HttpStatusCode::BadRequest}},
            {E::IncorrectNumberOfFilesInPostRequest,
             {E::IncorrectNumberOfFilesInPostRequest, "IncorrectNumberOfFilesInPostRequest", "POST requires exactly one file upload per request.",
              HttpStatusCode::BadRequest}},
            {E::InlineDataTooLarge,
             {E::InlineDataTooLarge, "InlineDataTooLarge", "The inline data exceeds the maximum allowed size.", HttpStatusCode::BadRequest}},
            {E::InternalError, {E::InternalError, "InternalError", "An internal error occurred. Try again.", HttpStatusCode::InternalServerError}},
            {E::InvalidAccessKeyId,
             {E::InvalidAccessKeyId, "InvalidAccessKeyId", "The AWS access key ID that you provided does not exist in our records.",
              HttpStatusCode::Forbidden}},
            {E::InvalidAccessPoint,
             {E::InvalidAccessPoint, "InvalidAccessPoint", "The specified access point name or account is not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidAccessPointAliasError,
             {E::InvalidAccessPointAliasError, "InvalidAccessPointAliasError", "The specified access point alias name is not valid.",
              HttpStatusCode::BadRequest}},
            {E::InvalidAddressingHeader,
             {E::InvalidAddressingHeader, "InvalidAddressingHeader", "You must specify the Anonymous role.", HttpStatusCode::BadRequest}},
            {E::InvalidArgument, {E::InvalidArgument, "InvalidArgument", "The specified argument was not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidBucketAclWithObjectOwnership,
             {E::InvalidBucketAclWithObjectOwnership, "InvalidBucketAclWithObjectOwnership",
              "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting.", HttpStatusCode::BadRequest}},
            {E::InvalidBucketName, {E::InvalidBucketName, "InvalidBucketName", "The specified bucket is not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidBucketOwnerAWSAccountID,
             {E::InvalidBucketOwnerAWSAccountID, "InvalidBucketOwnerAWSAccountID",
              "The value of the expected bucket owner parameter must be an AWS account ID.", HttpStatusCode::BadRequest}},
            {E::InvalidBucketState,
             {E::InvalidBucketState, "InvalidBucketState", "The request is not valid for the current state of the bucket.",
              HttpStatusCode::Conflict}},
            {E::InvalidDigest,
             {E::InvalidDigest, "InvalidDigest", "The Content-MD5 or checksum value that you specified is not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidEncryptionAlgorithmError,
             {E::InvalidEncryptionAlgorithmError, "InvalidEncryptionAlgorithmError",
              "The encryption request that you specified is not valid. The valid value is AES256.", HttpStatusCode::BadRequest}},
            {E::InvalidHostHeader,
             {E::InvalidHostHeader, "InvalidHostHeader", "The host headers provided in the request used the incorrect style addressing.",
              HttpStatusCode::BadRequest}},
            {E::InvalidHttpMethod,
             {E::InvalidHttpMethod, "InvalidHttpMethod", "The request is made using an unexpected HTTP method.", HttpStatusCode::BadRequest}},
            {E::InvalidLocationConstraint,
             {E::InvalidLocationConstraint, "InvalidLocationConstraint", "The specified location (Region) constraint is not valid.",
              HttpStatusCode::BadRequest}},
            {E::InvalidObjectState,
             {E::InvalidObjectState, "InvalidObjectState", "The operation is not valid for the current state of the object.",
              HttpStatusCode::Forbidden}},
            {E::InvalidPart, {E::InvalidPart, "InvalidPart", "One or more of the specified parts could not be found.", HttpStatusCode::BadRequest}},
            {E::InvalidPartOrder,
             {E::InvalidPartOrder, "InvalidPartOrder", "The list of parts was not in ascending order.", HttpStatusCode::BadRequest}},
            {E::InvalidPayer, {E::InvalidPayer, "InvalidPayer", "All access to this object has been disabled.", HttpStatusCode::Forbidden}},
            {E::InvalidPolicyDocument,
             {E::InvalidPolicyDocument, "InvalidPolicyDocument",
              "The content of the form does not meet the conditions specified in the policy document.", HttpStatusCode::BadRequest}},
            {E::InvalidRange, {E::InvalidRange, "InvalidRange", "The requested range cannot be satisfied.", HttpStatusCode::RangeNotSatisfiable}},
            {E::InvalidRegion,
             {E::InvalidRegion, "InvalidRegion", "You've attempted to create a Multi-Region Access Point in a Region that you haven't opted in to.",
              HttpStatusCode::Forbidden}},
            {E::InvalidRequest,
             {E::InvalidRequest, "InvalidRequest", "The request is invalid for the current state or configuration.", HttpStatusCode::BadRequest}},
            {E::InvalidSessionException,
             {E::InvalidSessionException, "InvalidSessionException", "Returned if the session doesn't exist anymore because it timed out or expired.",
              HttpStatusCode::BadRequest}},
            {E::InvalidSignature,
             {E::InvalidSignature, "InvalidSignature",
              "The request signature that the server calculated does not match the signature that you provided.", HttpStatusCode::BadRequest}},
            {E::InvalidSecurity,
             {E::InvalidSecurity, "InvalidSecurity", "The provided security credentials are not valid.", HttpStatusCode::Forbidden}},
            {E::InvalidSOAPRequest, {E::InvalidSOAPRequest, "InvalidSOAPRequest", "The SOAP request body is not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidStorageClass,
             {E::InvalidStorageClass, "InvalidStorageClass", "The storage class that you specified is not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidTargetBucketForLogging,
             {E::InvalidTargetBucketForLogging, "InvalidTargetBucketForLogging",
              "The target bucket for logging either does not exist, is not owned by you, or does not have the appropriate grants for the "
              "log-delivery group.",
              HttpStatusCode::BadRequest}},
            {E::InvalidToken,
             {E::InvalidToken, "InvalidToken", "The provided token is malformed or otherwise not valid.", HttpStatusCode::BadRequest}},
            {E::InvalidURI, {E::InvalidURI, "InvalidURI", "The specified URI couldn't be parsed.", HttpStatusCode::BadRequest}},
            {E::KeyTooLongError, {E::KeyTooLongError, "KeyTooLongError", "Your key is too long.", HttpStatusCode::BadRequest}},
            {E::KMSDisabledException,
             {E::KMSDisabledException, "KMS.DisabledException", "The request was rejected because the specified KMS key is not enabled.",
              HttpStatusCode::BadRequest}},
            {E::KMSInvalidKeyUsageException,
             {E::KMSInvalidKeyUsageException, "KMS.InvalidKeyUsageException",
              "The request was rejected because the KeyUsage of the KMS key is incompatible with the API operation.", HttpStatusCode::BadRequest}},
            {E::KMSInvalidStateException,
             {E::KMSInvalidStateException, "KMS.KMSInvalidStateException",
              "The request was rejected because the state of the specified resource is not valid for this request.", HttpStatusCode::BadRequest}},
            {E::KMSNotFoundException,
             {E::KMSNotFoundException, "KMS.NotFoundException",
              "The request was rejected because the specified entity or resource could not be found.", HttpStatusCode::BadRequest}},
            {E::MalformedACLError,
             {E::MalformedACLError, "MalformedACLError",
              "The ACL that you provided was not well formed or did not validate against our published schema.", HttpStatusCode::BadRequest}},
            {E::MalformedPOSTRequest,
             {E::MalformedPOSTRequest, "MalformedPOSTRequest", "The body of your POST request is not well-formed multipart/form-data.",
              HttpStatusCode::BadRequest}},
            {E::MalformedXML,
             {E::MalformedXML, "MalformedXML", "The XML that you provided was not well formed or did not validate against our published schema.",
              HttpStatusCode::BadRequest}},
            {E::MaxMessageLengthExceeded,
             {E::MaxMessageLengthExceeded, "MaxMessageLengthExceeded", "Your request was too large.", HttpStatusCode::BadRequest}},
            {E::MaxPostPreDataLengthExceededError,
             {E::MaxPostPreDataLengthExceededError, "MaxPostPreDataLengthExceededError",
              "Your POST request fields preceding the upload file were too large.", HttpStatusCode::BadRequest}},
            {E::MetadataTooLarge,
             {E::MetadataTooLarge, "MetadataTooLarge", "Your metadata headers exceed the maximum allowed metadata size.",
              HttpStatusCode::BadRequest}},
            {E::MethodNotAllowed,
             {E::MethodNotAllowed, "MethodNotAllowed", "The specified method is not allowed against this resource.",
              HttpStatusCode::MethodNotAllowed}},
            {E::MissingAttachment,
             {E::MissingAttachment, "MissingAttachment", "A SOAP attachment was expected, but none was found.", HttpStatusCode::BadRequest}},
            {E::MissingAuthenticationToken,
             {E::MissingAuthenticationToken, "MissingAuthenticationToken", "The request was not signed.", HttpStatusCode::Forbidden}},
            {E::MissingContentLength,
             {E::MissingContentLength, "MissingContentLength", "You must provide the Content-Length HTTP header.", HttpStatusCode::LengthRequired}},
            {E::MissingRequestBodyError,
             {E::MissingRequestBodyError, "MissingRequestBodyError", "You sent an empty XML document as a request.", HttpStatusCode::BadRequest}},
            {E::MissingSecurityElement,
             {E::MissingSecurityElement, "MissingSecurityElement", "The SOAP 1.1 request is missing a security element.",
              HttpStatusCode::BadRequest}},
            {E::MissingSecurityHeader,
             {E::MissingSecurityHeader, "MissingSecurityHeader", "Your request is missing a required header.", HttpStatusCode::BadRequest}},
            {E::NoLoggingStatusForKey,
             {E::NoLoggingStatusForKey, "NoLoggingStatusForKey", "There is no such thing as a logging status subresource for a key.",
              HttpStatusCode::BadRequest}},
            {E::NoSuchAsyncRequest, {E::NoSuchAsyncRequest, "NoSuchAsyncRequest", "The specified request was not found.", HttpStatusCode::NotFound}},
            {E::NoSuchBucket, {E::NoSuchBucket, "NoSuchBucket", "The specified bucket does not exist.", HttpStatusCode::NotFound}},
            {E::NoSuchBucketPolicy,
             {E::NoSuchBucketPolicy, "NoSuchBucketPolicy", "The specified bucket does not have a bucket policy.", HttpStatusCode::NotFound}},
            {E::NoSuchCORSConfiguration,
             {E::NoSuchCORSConfiguration, "NoSuchCORSConfiguration", "The specified bucket does not have a CORS configuration.",
              HttpStatusCode::NotFound}},
            {E::NoSuchKey, {E::NoSuchKey, "NoSuchKey", "The specified key does not exist.", HttpStatusCode::NotFound}},
            {E::NoSuchLifecycleConfiguration,
             {E::NoSuchLifecycleConfiguration, "NoSuchLifecycleConfiguration", "The specified lifecycle configuration does not exist.",
              HttpStatusCode::NotFound}},
            {E::NoSuchMultiRegionAccessPoint,
             {E::NoSuchMultiRegionAccessPoint, "NoSuchMultiRegionAccessPoint", "The specified Multi-Region Access Point does not exist.",
              HttpStatusCode::NotFound}},
            {E::NoSuchObjectLockConfiguration,
             {E::NoSuchObjectLockConfiguration, "NoSuchObjectLockConfiguration", "The specified object does not have an ObjectLock configuration.",
              HttpStatusCode::NotFound}},
            {E::NoSuchWebsiteConfiguration,
             {E::NoSuchWebsiteConfiguration, "NoSuchWebsiteConfiguration", "The specified bucket does not have a website configuration.",
              HttpStatusCode::NotFound}},
            {E::NoSuchTagSet, {E::NoSuchTagSet, "NoSuchTagSet", "The specified tag does not exist.", HttpStatusCode::NotFound}},
            {E::NoSuchUpload, {E::NoSuchUpload, "NoSuchUpload", "The specified multipart upload does not exist.", HttpStatusCode::NotFound}},
            {E::NoSuchVersion,
             {E::NoSuchVersion, "NoSuchVersion", "The version ID specified in the request does not match an existing version.",
              HttpStatusCode::NotFound}},
            {E::NotDeviceOwnerError,
             {E::NotDeviceOwnerError, "NotDeviceOwnerError", "The device that generated the token is not owned by the authenticated user.",
              HttpStatusCode::BadRequest}},
            {E::NotImplemented,
             {E::NotImplemented, "NotImplemented", "A header that you provided implies functionality that is not implemented.",
              HttpStatusCode::NotImplemented}},
            {E::NotModified, {E::NotModified, "NotModified", "The resource was not changed.", HttpStatusCode::NotModified}},
            {E::NoTransformationDefined,
             {E::NoTransformationDefined, "NoTransformationDefined", "No transformation found for this Object Lambda Access Point.",
              HttpStatusCode::NotFound}},
            {E::NotSignedUp, {E::NotSignedUp, "NotSignedUp", "Your account is not signed up for the Amazon S3 service.", HttpStatusCode::Forbidden}},
            {E::ObjectLockConfigurationNotFoundError,
             {E::ObjectLockConfigurationNotFoundError, "ObjectLockConfigurationNotFoundError",
              "The Object Lock configuration does not exist for this bucket.", HttpStatusCode::NotFound}},
            {E::OwnershipControlsNotFoundError,
             {E::OwnershipControlsNotFoundError, "OwnershipControlsNotFoundError", "The bucket ownership controls were not found.",
              HttpStatusCode::NotFound}},
            {E::OperationAborted,
             {E::OperationAborted, "OperationAborted", "A conflicting conditional operation is currently in progress against this resource.",
              HttpStatusCode::Conflict}},
            {E::PermanentRedirect,
             {E::PermanentRedirect, "PermanentRedirect",
              "The bucket that you are attempting to access must be addressed using the specified endpoint.", HttpStatusCode::MovedPermanently}},
            {E::PermanentRedirectControlError,
             {E::PermanentRedirectControlError, "PermanentRedirectControlError",
              "The API operation you are attempting to access must be addressed using the specified endpoint.", HttpStatusCode::MovedPermanently}},
            {E::PreconditionFailed,
             {E::PreconditionFailed, "PreconditionFailed", "At least one of the preconditions that you specified did not hold.",
              HttpStatusCode::PreconditionFailed}},
            {E::Redirect,
             {E::Redirect, "Redirect", "Temporary redirect. You are being redirected to the bucket while the DNS server is being updated.",
              HttpStatusCode::TemporaryRedirect}},
            {E::RequestHeaderSectionTooLarge,
             {E::RequestHeaderSectionTooLarge, "RequestHeaderSectionTooLarge",
              "The request header and query parameters used to make the request exceed the maximum allowed size.", HttpStatusCode::BadRequest}},
            {E::RequestIsNotMultiPartContent,
             {E::RequestIsNotMultiPartContent, "RequestIsNotMultiPartContent",
              "A bucket POST request must be of the enclosure-type multipart/form-data.", HttpStatusCode::PreconditionFailed}},
            {E::RequestTimeoutError,
             {E::RequestTimeoutError, "RequestTimeout",
              "Your socket connection to the server was not read from or written to within the timeout period.", HttpStatusCode::BadRequest}},
            {E::RequestTimeTooSkewed,
             {E::RequestTimeTooSkewed, "RequestTimeTooSkewed", "The difference between the request time and the server's time is too large.",
              HttpStatusCode::Forbidden}},
            {E::RequestTorrentOfBucketError,
             {E::RequestTorrentOfBucketError, "RequestTorrentOfBucketError", "Requesting the torrent file of a bucket is not permitted.",
              HttpStatusCode::BadRequest}},
            {E::ResponseInterrupted,
             {E::ResponseInterrupted, "ResponseInterrupted",
              "Returned to the original caller when an error is encountered while reading the WriteGetObjectResponse body.",
              HttpStatusCode::BadRequest}},
            {E::RestoreAlreadyInProgress,
             {E::RestoreAlreadyInProgress, "RestoreAlreadyInProgress", "The object restore is already in progress.", HttpStatusCode::Conflict}},
            {E::ServerSideEncryptionConfigurationNotFoundError,
             {E::ServerSideEncryptionConfigurationNotFoundError, "ServerSideEncryptionConfigurationNotFoundError",
              "The server-side encryption configuration was not found.", HttpStatusCode::BadRequest}},
            {E::ServiceUnavailableError,
             {E::ServiceUnavailableError, "ServiceUnavailable", "Service is unable to handle request.", HttpStatusCode::ServiceUnavailable}},
            {E::SignatureDoesNotMatch,
             {E::SignatureDoesNotMatch, "SignatureDoesNotMatch",
              "The request signature that the server calculated does not match the signature that you provided.", HttpStatusCode::Forbidden}},
            {E::SlowDown, {E::SlowDown, "SlowDown", "Please reduce your request rate.", HttpStatusCode::ServiceUnavailable}},
            {E::SlowDown503, {E::SlowDown503, "503 SlowDown", "Slow Down", HttpStatusCode::ServiceUnavailable}},
            {E::TagPolicyException,
             {E::TagPolicyException, "TagPolicyException", "The tag policy does not allow the specified value for the following tag key.",
              HttpStatusCode::BadRequest}},
            {E::TemporaryRedirect,
             {E::TemporaryRedirect, "TemporaryRedirect", "You are being redirected to the bucket while the DNS server is being updated.",
              HttpStatusCode::TemporaryRedirect}},
            {E::TokenCodeInvalidError,
             {E::TokenCodeInvalidError, "TokenCodeInvalidError", "The serial number and/or token code you provided is not valid.",
              HttpStatusCode::BadRequest}},
            {E::TokenRefreshRequired,
             {E::TokenRefreshRequired, "TokenRefreshRequired", "The provided token must be refreshed.", HttpStatusCode::BadRequest}},
            {E::TooManyAccessPoints,
             {E::TooManyAccessPoints, "TooManyAccessPoints", "You have attempted to create more access points than are allowed for an account.",
              HttpStatusCode::BadRequest}},
            {E::TooManyBuckets,
             {E::TooManyBuckets, "TooManyBuckets", "You have attempted to create more buckets than are allowed for an account.",
              HttpStatusCode::BadRequest}},
            {E::TooManyMultiRegionAccessPointRegionsError,
             {E::TooManyMultiRegionAccessPointRegionsError, "TooManyMultiRegionAccessPointregionsError",
              "You have attempted to create a Multi-Region Access Point with more Regions than are allowed for an account.",
              HttpStatusCode::BadRequest}},
            {E::TooManyMultiRegionAccessPoints,
             {E::TooManyMultiRegionAccessPoints, "TooManyMultiRegionAccessPoints",
              "You have attempted to create more Multi-Region Access Points than are allowed for an account.", HttpStatusCode::BadRequest}},
            {E::UnauthorizedAccessError,
             {E::UnauthorizedAccessError, "UnauthorizedAccessError",
              "This request was rejected because the IP was unexpected or the bucket doesn't have an ICP license.", HttpStatusCode::Forbidden}},
            {E::UnexpectedContent,
             {E::UnexpectedContent, "UnexpectedContent", "This request contains unsupported content.", HttpStatusCode::BadRequest}},
            {E::UnexpectedIPError,
             {E::UnexpectedIPError, "UnexpectedIPError", "This request was rejected because the IP was unexpected.", HttpStatusCode::Forbidden}},
            {E::UnsupportedArgument,
             {E::UnsupportedArgument, "UnsupportedArgument", "The request contained an unsupported argument.", HttpStatusCode::BadRequest}},
            {E::UnsupportedSignature,
             {E::UnsupportedSignature, "UnsupportedSignature",
              "The provided request is signed with an unsupported STS Token version or the signature version is not supported.",
              HttpStatusCode::BadRequest}},
            {E::UnresolvableGrantByEmailAddress,
             {E::UnresolvableGrantByEmailAddress, "UnresolvableGrantByEmailAddress",
              "The email address that you provided does not match any account on record.", HttpStatusCode::BadRequest}},
            {E::UserKeyMustBeSpecified,
             {E::UserKeyMustBeSpecified, "UserKeyMustBeSpecified", "The bucket POST request must contain the specified field name.",
              HttpStatusCode::BadRequest}},
            {E::NoSuchAccessPoint,
             {E::NoSuchAccessPoint, "NoSuchAccessPoint", "The specified access point does not exist.", HttpStatusCode::NotFound}},
            {E::InvalidTag, {E::InvalidTag, "InvalidTag", "Your request contains tag input that is not valid.", HttpStatusCode::BadRequest}},
            {E::MalformedPolicy,
             {E::MalformedPolicy, "MalformedPolicy", "Your policy contains a principal that is not valid.", HttpStatusCode::BadRequest}},
            {E::Ok, {E::Ok, "", "", HttpStatusCode::OK}},
            {E::Unknown, {E::Unknown, "Unknown", "Unknown S3 error.", HttpStatusCode::InternalServerError}},
        };

        auto it = kTable.find(s3ErrorCode);
        if (it != kTable.end())
        {
            return it->second;
        }
        return kTable.at(E::Unknown);
    }
} // namespace s3