#ifndef ART_S3_S3_ERROR_HPP_INCLUDED
#define ART_S3_S3_ERROR_HPP_INCLUDED

#include <string>
#include <system_error>
namespace s3
{
    enum class S3Error
    {
        Success = 0,
        AccessControlListNotSupported = 1,
        AccessDenied = 2,
        AccessPointAlreadyOwnedByYou,
        AccountProblem,
        AllAccessDisabled,
        AmbiguousGrantByEmailAddress,
        AuthorizationHeaderMalformed,
        AuthorizationQueryParametersError,
        BadDigest,
        BucketAlreadyExists,
        BucketAlreadyOwnedByYou,
        BucketHasAccessPointsAttached,
        BucketNotEmpty,
        ClientTokenConflict,
        ConnectionClosedByRequester,
        ConditionalRequestConflict,
        CredentialsNotSupported,
        CrossLocationLoggingProhibited,
        DeviceNotActiveError,
        EndpointNotFound,
        EntityTooSmall,
        EntityTooLarge,
        ExpiredToken,
        IllegalLocationConstraintException,
        IllegalVersioningConfigurationException,
        IncompleteBody,
        IncorrectEndpoint,
        IncorrectNumberOfFilesInPostRequest,
        InlineDataTooLarge,
        InternalError,
        InvalidAccessKeyId,
        InvalidAccessPoint,
        InvalidAccessPointAliasError,
        InvalidAddressingHeader,
        InvalidArgument,
        InvalidBucketAclWithObjectOwnership,
        InvalidBucketName,
        InvalidBucketOwnerAWSAccountID,
        InvalidBucketState,
        InvalidDigest,
        InvalidEncryptionAlgorithmError,
        InvalidHostHeader,
        InvalidHttpMethod,
        InvalidLocationConstraint,
        InvalidObjectState,
        InvalidPart,
        InvalidPartOrder,
        InvalidPayer,
        InvalidPolicyDocument,
        InvalidRange,
        InvalidRegion,
        InvalidRequest,
        InvalidSessionException,
        InvalidSignature,
        InvalidSecurity,
        InvalidSOAPRequest,
        InvalidStorageClass,
        InvalidTargetBucketForLogging,
        InvalidToken,
        InvalidURI,
        KeyTooLongError,
        KMS_DisabledException,
        KMS_InvalidKeyUsageException,
        KMS_KMSInvalidStateException,
        KMS_NotFoundException,
        MalformedACLError,
        MalformedPOSTRequest,
        MalformedXML,
        MaxMessageLengthExceeded,
        MaxPostPreDataLengthExceededError,
        MetadataTooLarge,
        MethodNotAllowed,
        MissingAttachment,
        MissingAuthenticationToken,
        MissingContentLength,
        MissingRequestBodyError,
        MissingSecurityElement,
        MissingSecurityHeader,
        NoLoggingStatusForKey,
        NoSuchAsyncRequest,
        NoSuchBucket,
        NoSuchBucketPolicy,
        NoSuchCORSConfiguration,
        NoSuchKey,
        NoSuchLifecycleConfiguration,
        NoSuchMultiRegionAccessPoint,
        NoSuchObjectLockConfiguration,
        NoSuchWebsiteConfiguration,
        NoSuchTagSet,
        NoSuchUpload,
        NoSuchVersion,
        NotDeviceOwnerError,
        NotImplemented,
        NotModified,
        NoTransformationDefined,
        NotSignedUp,
        ObjectLockConfigurationNotFoundError,
        OwnershipControlsNotFoundError,
        OperationAborted,
        PermanentRedirect,
        PermanentRedirectControlError,
        PreconditionFailed,
        Redirect,
        RequestHeaderSectionTooLarge,
        RequestIsNotMultiPartContent,
        RequestTimeout,
        RequestTimeTooSkewed,
        RequestTorrentOfBucketError,
        ResponseInterrupted,
        RestoreAlreadyInProgress,
        ServerSideEncryptionConfigurationNotFoundError,
        ServiceUnavailable,
        SignatureDoesNotMatch,
        SlowDown,
        TagPolicyException,
        TemporaryRedirect,
        TokenCodeInvalidError,
        TokenRefreshRequired,
        TooManyAccessPoints,
        TooManyBuckets,
        TooManyMultiRegionAccessPointregionsError,
        TooManyMultiRegionAccessPoints,
        UnauthorizedAccessError,
        UnexpectedContent,
        UnexpectedIPError,
        UnsupportedArgument,
        UnsupportedSignature,
        UnresolvableGrantByEmailAddress,
        UserKeyMustBeSpecified,
        NoSuchAccessPoint,
        InvalidTag,
        MalformedPolicy,
        NoSuchResource,
        TooManyTags,
        InvalidOutpostState,
        NoSuchOutpost,
        UnsupportedOperation,
        InsufficientCapacity,
    };
    class S3ErrorCategory : public std::error_category
    {
    public:
        S3ErrorCategory() = default;
        S3ErrorCategory(const S3ErrorCategory&) = delete;
        S3ErrorCategory& operator=(const S3ErrorCategory&) = delete;
        const char* name() const noexcept override;
        std::string message(int ev) const override;
        static const S3ErrorCategory& instance() noexcept;
    };
    std::error_code make_error_code(s3::S3Error e) noexcept;
    const std::error_category& s3_error_category() noexcept;

} // namespace s3

namespace std
{
    template <> struct is_error_code_enum<s3::S3Error> : public true_type
    {};
} // namespace std

#endif