#pragma once

#include <string>

#include "s3_http.hpp"
namespace s3
{
    namespace err
    {
        // https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
        enum class S3ErrorCode
        {
            Ok = 0,
            Unknown = 1,
            AccessControlListNotSupported = 2,
            AccessDenied = 3,
            AccessPointAlreadyOwnedByYou = 4,
            AccountProblem = 5,
            AllAccessDisabled = 6,
            AmbiguousGrantByEmailAddress = 7,
            AuthorizationHeaderMalformed = 8,
            AuthorizationQueryParametersError = 9,
            BadDigest = 10,
            BucketAlreadyExists = 11,
            BucketAlreadyOwnedByYou = 12,
            BucketHasAccessPointsAttached = 13,
            BucketNotEmpty = 14,
            ClientTokenConflict = 15,
            ConnectionClosedByRequester = 16,
            ConditionalRequestConflict = 17,
            CredentialsNotSupported = 18,
            CrossLocationLoggingProhibited = 19,
            DeviceNotActiveError = 20,
            EndpointNotFound = 21,
            EntityTooSmall = 22,
            EntityTooLarge = 23,
            ExpiredToken = 24,
            IllegalLocationConstraintException = 25,
            IllegalVersioningConfigurationException = 26,
            IncompleteBody = 27,
            IncorrectEndpoint = 28,
            IncorrectNumberOfFilesInPostRequest = 29,
            InlineDataTooLarge = 30,
            InternalError = 31,
            InvalidAccessKeyId = 32,
            InvalidAccessPoint = 33,
            InvalidAccessPointAliasError = 34,
            InvalidAddressingHeader = 35,
            InvalidArgument = 36,
            InvalidBucketAclWithObjectOwnership = 37,
            InvalidBucketName = 38,
            InvalidBucketOwnerAWSAccountID = 39,
            InvalidBucketState = 40,
            InvalidDigest = 41,
            InvalidEncryptionAlgorithmError = 42,
            InvalidHostHeader = 43,
            InvalidHttpMethod = 44,
            InvalidLocationConstraint = 45,
            InvalidObjectState = 46,
            InvalidPart = 47,
            InvalidPartOrder = 48,
            InvalidPayer = 49,
            InvalidPolicyDocument = 50,
            InvalidRange = 51,
            InvalidRegion = 52,
            InvalidRequest = 53,
            InvalidSessionException = 54,
            InvalidSignature = 55,
            InvalidSecurity = 56,
            InvalidSOAPRequest = 57,
            InvalidStorageClass = 58,
            InvalidTargetBucketForLogging = 59,
            InvalidToken = 60,
            InvalidURI = 61,
            KeyTooLongError = 62,
            KMSDisabledException = 63,
            KMSInvalidKeyUsageException = 64,
            KMSInvalidStateException = 65,
            KMSNotFoundException = 66,
            MalformedACLError = 67,
            MalformedPOSTRequest = 68,
            MalformedXML = 69,
            MaxMessageLengthExceeded = 70,
            MaxPostPreDataLengthExceededError = 71,
            MetadataTooLarge = 72,
            MethodNotAllowed = 73,
            MissingAttachment = 74,
            MissingAuthenticationToken = 75,
            MissingContentLength = 76,
            MissingRequestBodyError = 77,
            MissingSecurityElement = 78,
            MissingSecurityHeader = 79,
            NoLoggingStatusForKey = 80,
            NoSuchAsyncRequest = 81,
            NoSuchBucket = 82,
            NoSuchBucketPolicy = 83,
            NoSuchCORSConfiguration = 84,
            NoSuchKey = 85,
            NoSuchLifecycleConfiguration = 86,
            NoSuchMultiRegionAccessPoint = 87,
            NoSuchObjectLockConfiguration = 88,
            NoSuchWebsiteConfiguration = 89,
            NoSuchTagSet = 90,
            NoSuchUpload = 91,
            NoSuchVersion = 92,
            NotDeviceOwnerError = 93,
            NotImplemented = 94,
            NotModified = 95,
            NoTransformationDefined = 96,
            NotSignedUp = 97,
            ObjectLockConfigurationNotFoundError = 98,
            OwnershipControlsNotFoundError = 99,
            OperationAborted = 100,
            PermanentRedirect = 101,
            PermanentRedirectControlError = 102,
            PreconditionFailed = 103,
            Redirect = 104,
            RequestHeaderSectionTooLarge = 105,
            RequestIsNotMultiPartContent = 106,
            RequestTimeoutError = 107,
            RequestTimeTooSkewed = 108,
            RequestTorrentOfBucketError = 109,
            ResponseInterrupted = 110,
            RestoreAlreadyInProgress = 111,
            ServerSideEncryptionConfigurationNotFoundError = 112,
            ServiceUnavailableError = 113,
            SignatureDoesNotMatch = 114,
            SlowDown = 115,
            SlowDown503 = 116,
            TagPolicyException = 117,
            TemporaryRedirect = 118,
            TokenCodeInvalidError = 119,
            TokenRefreshRequired = 120,
            TooManyAccessPoints = 121,
            TooManyBuckets = 122,
            TooManyMultiRegionAccessPointRegionsError = 123,
            TooManyMultiRegionAccessPoints = 124,
            UnauthorizedAccessError = 125,
            UnexpectedContent = 126,
            UnexpectedIPError = 127,
            UnsupportedArgument = 128,
            UnsupportedSignature = 129,
            UnresolvableGrantByEmailAddress = 130,
            UserKeyMustBeSpecified = 131,
            NoSuchAccessPoint = 132,
            InvalidTag = 133,
            MalformedPolicy = 134,
        };

        struct S3ErrorInfo
        {
            S3ErrorCode s3ErrorCode;
            const char* s3ErrorName;
            const char* s3ErrorDescription;
            http::HttpStatusCode httpStatusCode;
        };

        const S3ErrorInfo& getS3ErrorInfo(S3ErrorCode s3ErrorCode);

    } // namespace err
} // namespace s3
