#include "s3_error.hpp"

#include <unordered_map>

namespace
{
    const std::unordered_map<s3::err::S3ErrorCode, s3::err::S3ErrorInfo> kS3ErrorInfoTable = {
        {s3::err::S3ErrorCode::AccessControlListNotSupported,
         {s3::err::S3ErrorCode::AccessControlListNotSupported, "AccessControlListNotSupported", "The bucket does not allow ACLs.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::AccessDenied,
         {s3::err::S3ErrorCode::AccessDenied, "AccessDenied", "Access Denied", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::AccessPointAlreadyOwnedByYou,
         {s3::err::S3ErrorCode::AccessPointAlreadyOwnedByYou, "AccessPointAlreadyOwnedByYou",
          "An access point with an identical name already exists in your account.", s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::AccountProblem,
         {s3::err::S3ErrorCode::AccountProblem, "AccountProblem",
          "There is a problem with your AWS account that prevents the operation from completing successfully.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::AllAccessDisabled,
         {s3::err::S3ErrorCode::AllAccessDisabled, "AllAccessDisabled", "All access to this Amazon S3 resource has been disabled.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::AmbiguousGrantByEmailAddress,
         {s3::err::S3ErrorCode::AmbiguousGrantByEmailAddress, "AmbiguousGrantByEmailAddress",
          "The email address that you provided is associated with more than one account.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::AuthorizationHeaderMalformed,
         {s3::err::S3ErrorCode::AuthorizationHeaderMalformed, "AuthorizationHeaderMalformed",
          "The authorization header that you provided is not valid.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::AuthorizationQueryParametersError,
         {s3::err::S3ErrorCode::AuthorizationQueryParametersError, "AuthorizationQueryParametersError",
          "The authorization query parameters that you provided are not valid.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::BadDigest,
         {s3::err::S3ErrorCode::BadDigest, "BadDigest",
          "The Content-MD5 or checksum value that you specified did not match what the server received.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::BucketAlreadyExists,
         {s3::err::S3ErrorCode::BucketAlreadyExists, "BucketAlreadyExists", "The requested bucket name is not available.",
          s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::BucketAlreadyOwnedByYou,
         {s3::err::S3ErrorCode::BucketAlreadyOwnedByYou, "BucketAlreadyOwnedByYou",
          "The bucket that you tried to create already exists, and you own it.", s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::BucketHasAccessPointsAttached,
         {s3::err::S3ErrorCode::BucketHasAccessPointsAttached, "BucketHasAccessPointsAttached",
          "The bucket you tried to delete has access points attached.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::BucketNotEmpty,
         {s3::err::S3ErrorCode::BucketNotEmpty, "BucketNotEmpty", "The bucket that you tried to delete is not empty.",
          s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::ClientTokenConflict,
         {s3::err::S3ErrorCode::ClientTokenConflict, "ClientTokenConflict",
          "Your Multi-Region Access Point idempotency token was already used for a different request.", s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::ConnectionClosedByRequester,
         {s3::err::S3ErrorCode::ConnectionClosedByRequester, "ConnectionClosedByRequester",
          "Returned to the original caller when an error is encountered while reading the WriteGetObjectResponse body.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::ConditionalRequestConflict,
         {s3::err::S3ErrorCode::ConditionalRequestConflict, "ConditionalRequestConflict", "A conflicting operation occurred.",
          s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::CredentialsNotSupported,
         {s3::err::S3ErrorCode::CredentialsNotSupported, "CredentialsNotSupported", "This request does not support credentials.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::CrossLocationLoggingProhibited,
         {s3::err::S3ErrorCode::CrossLocationLoggingProhibited, "CrossLocationLoggingProhibited", "Cross-Region logging is not allowed.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::DeviceNotActiveError,
         {s3::err::S3ErrorCode::DeviceNotActiveError, "DeviceNotActiveError", "The device is not currently active.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::EndpointNotFound,
         {s3::err::S3ErrorCode::EndpointNotFound, "EndpointNotFound", "Direct requests to the correct endpoint.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::EntityTooSmall,
         {s3::err::S3ErrorCode::EntityTooSmall, "EntityTooSmall", "Your proposed upload is smaller than the minimum allowed object size.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::EntityTooLarge,
         {s3::err::S3ErrorCode::EntityTooLarge, "EntityTooLarge", "Your proposed upload exceeds the maximum allowed object size.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::ExpiredToken,
         {s3::err::S3ErrorCode::ExpiredToken, "ExpiredToken", "The provided token has expired.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::IllegalLocationConstraintException,
         {s3::err::S3ErrorCode::IllegalLocationConstraintException, "IllegalLocationConstraintException",
          "The specified location constraint is not valid for this request.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::IllegalVersioningConfigurationException,
         {s3::err::S3ErrorCode::IllegalVersioningConfigurationException, "IllegalVersioningConfigurationException",
          "The versioning configuration specified in the request is not valid.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::IncompleteBody,
         {s3::err::S3ErrorCode::IncompleteBody, "IncompleteBody",
          "You did not provide the number of bytes specified by the Content-Length HTTP header.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::IncorrectEndpoint,
         {s3::err::S3ErrorCode::IncorrectEndpoint, "IncorrectEndpoint", "The specified bucket exists in another Region.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::IncorrectNumberOfFilesInPostRequest,
         {s3::err::S3ErrorCode::IncorrectNumberOfFilesInPostRequest, "IncorrectNumberOfFilesInPostRequest",
          "POST requires exactly one file upload per request.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InlineDataTooLarge,
         {s3::err::S3ErrorCode::InlineDataTooLarge, "InlineDataTooLarge", "The inline data exceeds the maximum allowed size.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InternalError,
         {s3::err::S3ErrorCode::InternalError, "InternalError", "An internal error occurred. Try again.",
          s3::http::HttpStatusCode::InternalServerError}},
        {s3::err::S3ErrorCode::InvalidAccessKeyId,
         {s3::err::S3ErrorCode::InvalidAccessKeyId, "InvalidAccessKeyId", "The AWS access key ID that you provided does not exist in our records.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::InvalidAccessPoint,
         {s3::err::S3ErrorCode::InvalidAccessPoint, "InvalidAccessPoint", "The specified access point name or account is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidAccessPointAliasError,
         {s3::err::S3ErrorCode::InvalidAccessPointAliasError, "InvalidAccessPointAliasError", "The specified access point alias name is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidAddressingHeader,
         {s3::err::S3ErrorCode::InvalidAddressingHeader, "InvalidAddressingHeader", "You must specify the Anonymous role.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidArgument,
         {s3::err::S3ErrorCode::InvalidArgument, "InvalidArgument", "The specified argument was not valid.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidBucketAclWithObjectOwnership,
         {s3::err::S3ErrorCode::InvalidBucketAclWithObjectOwnership, "InvalidBucketAclWithObjectOwnership",
          "Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidBucketName,
         {s3::err::S3ErrorCode::InvalidBucketName, "InvalidBucketName", "The specified bucket is not valid.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidBucketOwnerAWSAccountID,
         {s3::err::S3ErrorCode::InvalidBucketOwnerAWSAccountID, "InvalidBucketOwnerAWSAccountID",
          "The value of the expected bucket owner parameter must be an AWS account ID.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidBucketState,
         {s3::err::S3ErrorCode::InvalidBucketState, "InvalidBucketState", "The request is not valid for the current state of the bucket.",
          s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::InvalidDigest,
         {s3::err::S3ErrorCode::InvalidDigest, "InvalidDigest", "The Content-MD5 or checksum value that you specified is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidEncryptionAlgorithmError,
         {s3::err::S3ErrorCode::InvalidEncryptionAlgorithmError, "InvalidEncryptionAlgorithmError",
          "The encryption request that you specified is not valid. The valid value is AES256.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidHostHeader,
         {s3::err::S3ErrorCode::InvalidHostHeader, "InvalidHostHeader",
          "The host headers provided in the request used the incorrect style addressing.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidHttpMethod,
         {s3::err::S3ErrorCode::InvalidHttpMethod, "InvalidHttpMethod", "The request is made using an unexpected HTTP method.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidLocationConstraint,
         {s3::err::S3ErrorCode::InvalidLocationConstraint, "InvalidLocationConstraint", "The specified location (Region) constraint is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidObjectState,
         {s3::err::S3ErrorCode::InvalidObjectState, "InvalidObjectState", "The operation is not valid for the current state of the object.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::InvalidPart,
         {s3::err::S3ErrorCode::InvalidPart, "InvalidPart", "One or more of the specified parts could not be found.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidPartOrder,
         {s3::err::S3ErrorCode::InvalidPartOrder, "InvalidPartOrder", "The list of parts was not in ascending order.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidPayer,
         {s3::err::S3ErrorCode::InvalidPayer, "InvalidPayer", "All access to this object has been disabled.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::InvalidPolicyDocument,
         {s3::err::S3ErrorCode::InvalidPolicyDocument, "InvalidPolicyDocument",
          "The content of the form does not meet the conditions specified in the policy document.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidRange,
         {s3::err::S3ErrorCode::InvalidRange, "InvalidRange", "The requested range cannot be satisfied.",
          s3::http::HttpStatusCode::RangeNotSatisfiable}},
        {s3::err::S3ErrorCode::InvalidRegion,
         {s3::err::S3ErrorCode::InvalidRegion, "InvalidRegion",
          "You've attempted to create a Multi-Region Access Point in a Region that you haven't opted in to.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::InvalidRequest,
         {s3::err::S3ErrorCode::InvalidRequest, "InvalidRequest", "The request is invalid for the current state or configuration.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidSessionException,
         {s3::err::S3ErrorCode::InvalidSessionException, "InvalidSessionException",
          "Returned if the session doesn't exist anymore because it timed out or expired.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidSignature,
         {s3::err::S3ErrorCode::InvalidSignature, "InvalidSignature",
          "The request signature that the server calculated does not match the signature that you provided.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidSecurity,
         {s3::err::S3ErrorCode::InvalidSecurity, "InvalidSecurity", "The provided security credentials are not valid.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::InvalidSOAPRequest,
         {s3::err::S3ErrorCode::InvalidSOAPRequest, "InvalidSOAPRequest", "The SOAP request body is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidStorageClass,
         {s3::err::S3ErrorCode::InvalidStorageClass, "InvalidStorageClass", "The storage class that you specified is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidTargetBucketForLogging,
         {s3::err::S3ErrorCode::InvalidTargetBucketForLogging, "InvalidTargetBucketForLogging",
          "The target bucket for logging either does not exist, is not owned by you, or does not have the appropriate grants for the "
          "log-delivery group.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidToken,
         {s3::err::S3ErrorCode::InvalidToken, "InvalidToken", "The provided token is malformed or otherwise not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::InvalidURI,
         {s3::err::S3ErrorCode::InvalidURI, "InvalidURI", "The specified URI couldn't be parsed.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::KeyTooLongError,
         {s3::err::S3ErrorCode::KeyTooLongError, "KeyTooLongError", "Your key is too long.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::KMSDisabledException,
         {s3::err::S3ErrorCode::KMSDisabledException, "KMS.DisabledException",
          "The request was rejected because the specified KMS key is not enabled.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::KMSInvalidKeyUsageException,
         {s3::err::S3ErrorCode::KMSInvalidKeyUsageException, "KMS.InvalidKeyUsageException",
          "The request was rejected because the KeyUsage of the KMS key is incompatible with the API operation.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::KMSInvalidStateException,
         {s3::err::S3ErrorCode::KMSInvalidStateException, "KMS.KMSInvalidStateException",
          "The request was rejected because the state of the specified resource is not valid for this request.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::KMSNotFoundException,
         {s3::err::S3ErrorCode::KMSNotFoundException, "KMS.NotFoundException",
          "The request was rejected because the specified entity or resource could not be found.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MalformedACLError,
         {s3::err::S3ErrorCode::MalformedACLError, "MalformedACLError",
          "The ACL that you provided was not well formed or did not validate against our published schema.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MalformedPOSTRequest,
         {s3::err::S3ErrorCode::MalformedPOSTRequest, "MalformedPOSTRequest", "The body of your POST request is not well-formed multipart/form-data.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MalformedXML,
         {s3::err::S3ErrorCode::MalformedXML, "MalformedXML",
          "The XML that you provided was not well formed or did not validate against our published schema.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MaxMessageLengthExceeded,
         {s3::err::S3ErrorCode::MaxMessageLengthExceeded, "MaxMessageLengthExceeded", "Your request was too large.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MaxPostPreDataLengthExceededError,
         {s3::err::S3ErrorCode::MaxPostPreDataLengthExceededError, "MaxPostPreDataLengthExceededError",
          "Your POST request fields preceding the upload file were too large.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MetadataTooLarge,
         {s3::err::S3ErrorCode::MetadataTooLarge, "MetadataTooLarge", "Your metadata headers exceed the maximum allowed metadata size.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MethodNotAllowed,
         {s3::err::S3ErrorCode::MethodNotAllowed, "MethodNotAllowed", "The specified method is not allowed against this resource.",
          s3::http::HttpStatusCode::MethodNotAllowed}},
        {s3::err::S3ErrorCode::MissingAttachment,
         {s3::err::S3ErrorCode::MissingAttachment, "MissingAttachment", "A SOAP attachment was expected, but none was found.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MissingAuthenticationToken,
         {s3::err::S3ErrorCode::MissingAuthenticationToken, "MissingAuthenticationToken", "The request was not signed.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::MissingContentLength,
         {s3::err::S3ErrorCode::MissingContentLength, "MissingContentLength", "You must provide the Content-Length HTTP header.",
          s3::http::HttpStatusCode::LengthRequired}},
        {s3::err::S3ErrorCode::MissingRequestBodyError,
         {s3::err::S3ErrorCode::MissingRequestBodyError, "MissingRequestBodyError", "You sent an empty XML document as a request.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MissingSecurityElement,
         {s3::err::S3ErrorCode::MissingSecurityElement, "MissingSecurityElement", "The SOAP 1.1 request is missing a security element.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MissingSecurityHeader,
         {s3::err::S3ErrorCode::MissingSecurityHeader, "MissingSecurityHeader", "Your request is missing a required header.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::NoLoggingStatusForKey,
         {s3::err::S3ErrorCode::NoLoggingStatusForKey, "NoLoggingStatusForKey", "There is no such thing as a logging status subresource for a key.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::NoSuchAsyncRequest,
         {s3::err::S3ErrorCode::NoSuchAsyncRequest, "NoSuchAsyncRequest", "The specified request was not found.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchBucket,
         {s3::err::S3ErrorCode::NoSuchBucket, "NoSuchBucket", "The specified bucket does not exist.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchBucketPolicy,
         {s3::err::S3ErrorCode::NoSuchBucketPolicy, "NoSuchBucketPolicy", "The specified bucket does not have a bucket policy.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchCORSConfiguration,
         {s3::err::S3ErrorCode::NoSuchCORSConfiguration, "NoSuchCORSConfiguration", "The specified bucket does not have a CORS configuration.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchKey,
         {s3::err::S3ErrorCode::NoSuchKey, "NoSuchKey", "The specified key does not exist.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchLifecycleConfiguration,
         {s3::err::S3ErrorCode::NoSuchLifecycleConfiguration, "NoSuchLifecycleConfiguration", "The specified lifecycle configuration does not exist.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchMultiRegionAccessPoint,
         {s3::err::S3ErrorCode::NoSuchMultiRegionAccessPoint, "NoSuchMultiRegionAccessPoint",
          "The specified Multi-Region Access Point does not exist.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchObjectLockConfiguration,
         {s3::err::S3ErrorCode::NoSuchObjectLockConfiguration, "NoSuchObjectLockConfiguration",
          "The specified object does not have an ObjectLock configuration.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchWebsiteConfiguration,
         {s3::err::S3ErrorCode::NoSuchWebsiteConfiguration, "NoSuchWebsiteConfiguration",
          "The specified bucket does not have a website configuration.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchTagSet,
         {s3::err::S3ErrorCode::NoSuchTagSet, "NoSuchTagSet", "The specified tag does not exist.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchUpload,
         {s3::err::S3ErrorCode::NoSuchUpload, "NoSuchUpload", "The specified multipart upload does not exist.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NoSuchVersion,
         {s3::err::S3ErrorCode::NoSuchVersion, "NoSuchVersion", "The version ID specified in the request does not match an existing version.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NotDeviceOwnerError,
         {s3::err::S3ErrorCode::NotDeviceOwnerError, "NotDeviceOwnerError",
          "The device that generated the token is not owned by the authenticated user.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::NotImplemented,
         {s3::err::S3ErrorCode::NotImplemented, "NotImplemented", "A header that you provided implies functionality that is not implemented.",
          s3::http::HttpStatusCode::NotImplemented}},
        {s3::err::S3ErrorCode::NotModified,
         {s3::err::S3ErrorCode::NotModified, "NotModified", "The resource was not changed.", s3::http::HttpStatusCode::NotModified}},
        {s3::err::S3ErrorCode::NoTransformationDefined,
         {s3::err::S3ErrorCode::NoTransformationDefined, "NoTransformationDefined", "No transformation found for this Object Lambda Access Point.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::NotSignedUp,
         {s3::err::S3ErrorCode::NotSignedUp, "NotSignedUp", "Your account is not signed up for the Amazon S3 service.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::ObjectLockConfigurationNotFoundError,
         {s3::err::S3ErrorCode::ObjectLockConfigurationNotFoundError, "ObjectLockConfigurationNotFoundError",
          "The Object Lock configuration does not exist for this bucket.", s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::OwnershipControlsNotFoundError,
         {s3::err::S3ErrorCode::OwnershipControlsNotFoundError, "OwnershipControlsNotFoundError", "The bucket ownership controls were not found.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::OperationAborted,
         {s3::err::S3ErrorCode::OperationAborted, "OperationAborted",
          "A conflicting conditional operation is currently in progress against this resource.", s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::PermanentRedirect,
         {s3::err::S3ErrorCode::PermanentRedirect, "PermanentRedirect",
          "The bucket that you are attempting to access must be addressed using the specified endpoint.",
          s3::http::HttpStatusCode::MovedPermanently}},
        {s3::err::S3ErrorCode::PermanentRedirectControlError,
         {s3::err::S3ErrorCode::PermanentRedirectControlError, "PermanentRedirectControlError",
          "The API operation you are attempting to access must be addressed using the specified endpoint.",
          s3::http::HttpStatusCode::MovedPermanently}},
        {s3::err::S3ErrorCode::PreconditionFailed,
         {s3::err::S3ErrorCode::PreconditionFailed, "PreconditionFailed", "At least one of the preconditions that you specified did not hold.",
          s3::http::HttpStatusCode::PreconditionFailed}},
        {s3::err::S3ErrorCode::Redirect,
         {s3::err::S3ErrorCode::Redirect, "Redirect",
          "Temporary redirect. You are being redirected to the bucket while the DNS server is being updated.",
          s3::http::HttpStatusCode::TemporaryRedirect}},
        {s3::err::S3ErrorCode::RequestHeaderSectionTooLarge,
         {s3::err::S3ErrorCode::RequestHeaderSectionTooLarge, "RequestHeaderSectionTooLarge",
          "The request header and query parameters used to make the request exceed the maximum allowed size.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::RequestIsNotMultiPartContent,
         {s3::err::S3ErrorCode::RequestIsNotMultiPartContent, "RequestIsNotMultiPartContent",
          "A bucket POST request must be of the enclosure-type multipart/form-data.", s3::http::HttpStatusCode::PreconditionFailed}},
        {s3::err::S3ErrorCode::RequestTimeoutError,
         {s3::err::S3ErrorCode::RequestTimeoutError, "RequestTimeout",
          "Your socket connection to the server was not read from or written to within the timeout period.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::RequestTimeTooSkewed,
         {s3::err::S3ErrorCode::RequestTimeTooSkewed, "RequestTimeTooSkewed",
          "The difference between the request time and the server's time is too large.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::RequestTorrentOfBucketError,
         {s3::err::S3ErrorCode::RequestTorrentOfBucketError, "RequestTorrentOfBucketError",
          "Requesting the torrent file of a bucket is not permitted.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::ResponseInterrupted,
         {s3::err::S3ErrorCode::ResponseInterrupted, "ResponseInterrupted",
          "Returned to the original caller when an error is encountered while reading the WriteGetObjectResponse body.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::RestoreAlreadyInProgress,
         {s3::err::S3ErrorCode::RestoreAlreadyInProgress, "RestoreAlreadyInProgress", "The object restore is already in progress.",
          s3::http::HttpStatusCode::Conflict}},
        {s3::err::S3ErrorCode::ServerSideEncryptionConfigurationNotFoundError,
         {s3::err::S3ErrorCode::ServerSideEncryptionConfigurationNotFoundError, "ServerSideEncryptionConfigurationNotFoundError",
          "The server-side encryption configuration was not found.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::ServiceUnavailableError,
         {s3::err::S3ErrorCode::ServiceUnavailableError, "ServiceUnavailable", "Service is unable to handle request.",
          s3::http::HttpStatusCode::ServiceUnavailable}},
        {s3::err::S3ErrorCode::SignatureDoesNotMatch,
         {s3::err::S3ErrorCode::SignatureDoesNotMatch, "SignatureDoesNotMatch",
          "The request signature that the server calculated does not match the signature that you provided.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::SlowDown,
         {s3::err::S3ErrorCode::SlowDown, "SlowDown", "Please reduce your request rate.", s3::http::HttpStatusCode::ServiceUnavailable}},
        {s3::err::S3ErrorCode::SlowDown503,
         {s3::err::S3ErrorCode::SlowDown503, "503 SlowDown", "Slow Down", s3::http::HttpStatusCode::ServiceUnavailable}},
        {s3::err::S3ErrorCode::TagPolicyException,
         {s3::err::S3ErrorCode::TagPolicyException, "TagPolicyException",
          "The tag policy does not allow the specified value for the following tag key.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TemporaryRedirect,
         {s3::err::S3ErrorCode::TemporaryRedirect, "TemporaryRedirect",
          "You are being redirected to the bucket while the DNS server is being updated.", s3::http::HttpStatusCode::TemporaryRedirect}},
        {s3::err::S3ErrorCode::TokenCodeInvalidError,
         {s3::err::S3ErrorCode::TokenCodeInvalidError, "TokenCodeInvalidError", "The serial number and/or token code you provided is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TokenRefreshRequired,
         {s3::err::S3ErrorCode::TokenRefreshRequired, "TokenRefreshRequired", "The provided token must be refreshed.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TooManyAccessPoints,
         {s3::err::S3ErrorCode::TooManyAccessPoints, "TooManyAccessPoints",
          "You have attempted to create more access points than are allowed for an account.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TooManyBuckets,
         {s3::err::S3ErrorCode::TooManyBuckets, "TooManyBuckets", "You have attempted to create more buckets than are allowed for an account.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TooManyMultiRegionAccessPointRegionsError,
         {s3::err::S3ErrorCode::TooManyMultiRegionAccessPointRegionsError, "TooManyMultiRegionAccessPointregionsError",
          "You have attempted to create a Multi-Region Access Point with more Regions than are allowed for an account.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::TooManyMultiRegionAccessPoints,
         {s3::err::S3ErrorCode::TooManyMultiRegionAccessPoints, "TooManyMultiRegionAccessPoints",
          "You have attempted to create more Multi-Region Access Points than are allowed for an account.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::UnauthorizedAccessError,
         {s3::err::S3ErrorCode::UnauthorizedAccessError, "UnauthorizedAccessError",
          "This request was rejected because the IP was unexpected or the bucket doesn't have an ICP license.", s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::UnexpectedContent,
         {s3::err::S3ErrorCode::UnexpectedContent, "UnexpectedContent", "This request contains unsupported content.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::UnexpectedIPError,
         {s3::err::S3ErrorCode::UnexpectedIPError, "UnexpectedIPError", "This request was rejected because the IP was unexpected.",
          s3::http::HttpStatusCode::Forbidden}},
        {s3::err::S3ErrorCode::UnsupportedArgument,
         {s3::err::S3ErrorCode::UnsupportedArgument, "UnsupportedArgument", "The request contained an unsupported argument.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::UnsupportedSignature,
         {s3::err::S3ErrorCode::UnsupportedSignature, "UnsupportedSignature",
          "The provided request is signed with an unsupported STS Token version or the signature version is not supported.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::UnresolvableGrantByEmailAddress,
         {s3::err::S3ErrorCode::UnresolvableGrantByEmailAddress, "UnresolvableGrantByEmailAddress",
          "The email address that you provided does not match any account on record.", s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::UserKeyMustBeSpecified,
         {s3::err::S3ErrorCode::UserKeyMustBeSpecified, "UserKeyMustBeSpecified", "The bucket POST request must contain the specified field name.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::NoSuchAccessPoint,
         {s3::err::S3ErrorCode::NoSuchAccessPoint, "NoSuchAccessPoint", "The specified access point does not exist.",
          s3::http::HttpStatusCode::NotFound}},
        {s3::err::S3ErrorCode::InvalidTag,
         {s3::err::S3ErrorCode::InvalidTag, "InvalidTag", "Your request contains tag input that is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::MalformedPolicy,
         {s3::err::S3ErrorCode::MalformedPolicy, "MalformedPolicy", "Your policy contains a principal that is not valid.",
          s3::http::HttpStatusCode::BadRequest}},
        {s3::err::S3ErrorCode::Ok, {s3::err::S3ErrorCode::Ok, "", "", s3::http::HttpStatusCode::OK}},
        {s3::err::S3ErrorCode::Unknown,
         {s3::err::S3ErrorCode::Unknown, "Unknown", "Unknown S3 error.", s3::http::HttpStatusCode::InternalServerError}},
    };

} // namespace

namespace s3
{
    namespace err
    {
        const s3::err::S3ErrorInfo& getS3ErrorInfo(s3::err::S3ErrorCode s3ErrorCode)
        {
            auto it = kS3ErrorInfoTable.find(s3ErrorCode);
            if (it != kS3ErrorInfoTable.end())
            {
                return it->second;
            }
            return kS3ErrorInfoTable.at(s3::err::S3ErrorCode::Unknown);
        }
    } // namespace err
} // namespace s3